// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `index_to_utxo_list`

Future<SelectionOutput> selectCoinBnb({
  required List<OutputGroup> inputs,
  required CoinSelectionOpt options,
}) => RustLib.instance.api.crateAlgorithmsBnbSelectCoinBnb(
  inputs: inputs,
  options: options,
);
