// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_lookahead`, `build_min_tail_weight`, `index_to_original_indices`, `is_remaining_weight_higher`, `result_check`, `result`

/// Deterministic Branch and Bound search that minimizes the input weight.
///
/// This algorithm selects the set of inputs that meets the `total_target` and has the lowest
/// total weight.  In so doing, a change output is created unlike the vanilla Branch and Bound
/// algorithm.  Therefore, in order to ensure that the change output can be paid for, the
/// `total_target` is calculated as `target` plus `change_target` where `change_target`.  The
/// `change_target` is the budgeted amount to pay for the change output.
///
/// See also: [bitcoin coin selection](https://github.com/bitcoin/bitcoin/blob/62bd61de110b057cbfd6e31e4d0b727d93119c72/src/wallet/coinselection.cpp#L204)
///
/// There is discussion [here](https://murch.one/erhardt2016coinselection.pdf) at section 6.4.3
/// that prioritizing input weight will lead to a fragmentation of the UTXO set.  Therefore, prefer
/// this search only in extreme conditions where fee_rate is high, since a set of UTXOs with minimal
/// weight will lead to a cheaper constructed transaction in the short term.  However, in the
/// long-term, this prioritization can lead to more UTXOs to choose from.
Future<SelectionOutput> coinGrinder({
  required List<OutputGroup> weightedUtxos,
  required CoinSelectionOpt options,
}) => RustLib.instance.api.crateAlgorithmsCoinGrinderCoinGrinder(
  weightedUtxos: weightedUtxos,
  options: options,
);
