// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BnBState`

/// Selects inputs using BnB to first minimize change and then the input count.
Future<SelectionOutput> selectCoinBnbLeastchange({
  required List<OutputGroup> inputs,
  required CoinSelectionOpt options,
}) => RustLib.instance.api.crateAlgorithmsLeastchangeSelectCoinBnbLeastchange(
  inputs: inputs,
  options: options,
);
